# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wallboy < Formula
  desc "Cross-platform wallpaper manager with auto-rotation"
  homepage "https://github.com/Artawower/wallboy"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Artawower/wallboy/releases/download/v0.2.1/wallboy_0.2.1_darwin_amd64.tar.gz"
      sha256 "9e7a54c3fc9e2e08f81d229411948992f56e5446dc580ba179f364e8cdd945b1"

      def install
        bin.install "wallboy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Artawower/wallboy/releases/download/v0.2.1/wallboy_0.2.1_darwin_arm64.tar.gz"
      sha256 "349d554253e6ce638b61602d1de8444f7cc3e4c938248896374b5a9d5f528ce6"

      def install
        bin.install "wallboy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Artawower/wallboy/releases/download/v0.2.1/wallboy_0.2.1_linux_amd64.tar.gz"
      sha256 "63ab510732c58e9b8378c0fa8982bfed7a4407f031b642abc946c5944e64a27e"
      def install
        bin.install "wallboy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Artawower/wallboy/releases/download/v0.2.1/wallboy_0.2.1_linux_arm64.tar.gz"
      sha256 "b99b060cb4706cf75a861c96aea5e30337d1c63b05c65dcb462f5615376253fc"
      def install
        bin.install "wallboy"
      end
    end
  end

  test do
    system "#{bin}/wallboy", "version"
  end
end
