# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wallboy < Formula
  desc "Cross-platform wallpaper manager with auto-rotation"
  homepage "https://github.com/Artawower/wallboy"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Artawower/wallboy/releases/download/v0.1.7/wallboy_0.1.7_darwin_amd64.tar.gz"
      sha256 "12a69703bf08bba5ce04785b9cb4fd9f81aa8b9686c7c4b08020e6e55fc2060a"

      def install
        bin.install "wallboy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Artawower/wallboy/releases/download/v0.1.7/wallboy_0.1.7_darwin_arm64.tar.gz"
      sha256 "4d0fd9d19080237e0ba2bff8f742d4928cb15098d214a9e6b360d3b113e72fca"

      def install
        bin.install "wallboy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Artawower/wallboy/releases/download/v0.1.7/wallboy_0.1.7_linux_amd64.tar.gz"
      sha256 "16637524bae6292a0ecc34c4759b409662847fc4ea2f5b9a6bbab9dec216e9a0"
      def install
        bin.install "wallboy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Artawower/wallboy/releases/download/v0.1.7/wallboy_0.1.7_linux_arm64.tar.gz"
      sha256 "6c8a88b9c5fc954f6693e1feaa27e9a413e50031b54be9179a91f580b7d2c28a"
      def install
        bin.install "wallboy"
      end
    end
  end

  test do
    system "#{bin}/wallboy", "version"
  end
end
